import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import { cn } from '@/shared/lib/css';
import { Header } from './_widgets/header/header';

const fontSans = FontSans({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-sans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    `${fontSans.variable} antialiased min-h-screen bg-background dark flex flex-col`,
                )}>
                <Header />
                {children}
            </body>
        </html>
    );
}
